// <auto-generated />
namespace SimpleBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Posts_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Posts_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050826584_Posts_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
